name: Falcon API Request
on:
  push:
    branches:
      - main
jobs:
  request:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Make Falcon API Request
      env:
        FALCON_CLIENT_ID: "19e063dd2f834679b091dfea627450c5"
        FALCON_CLIENT_SECRET: "ier9dDPOpWcz7ybmZM1FCG8S0JHLju4sK5k36A2o"
        FALCON_CID: "A3839C9ECA014C70B7DB136F279AE499-C7"
      run: |
        # Fetch the latest sensor version with required environment variables
        LATEST_SENSOR=$(FALCON_CLIENT_ID=$FALCON_CLIENT_ID \
                        FALCON_CLIENT_SECRET=$FALCON_CLIENT_SECRET \
                        FALCON_CID=$FALCON_CID \
                        bash <(curl -Ls https://github.com/CrowdStrike/falcon-scripts/releases/latest/download/falcon-container-sensor-pull.sh) \
                        -t falcon-container | tail -1)
        echo "LATEST_SENSOR=$LATEST_SENSOR" >> $GITHUB_ENV

    - name: Compare Sensor Version
      id: compare
      run: |
        PREDEFINED_VERSION="1.2.3" 
        # Compare the fetched sensor version with the predefined version
        if [ "$LATEST_SENSOR" == "$PREDEFINED_VERSION" ]; then
          echo "Versions match" 
        else
          echo "Versions do not match" 
        fi

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: "ASIAS5ZSGPJ3D36SCRXR"
        aws-secret-access-key: "X5/OXhmhIytObNPahE3fWOzG+mSJB3i+BWw8wV4y"
        aws-session-token: "IQoJb3JpZ2luX2VjEEgaCXVzLWVhc3QtMSJIMEYCIQCR7dPZQtgqIrmePGZpYqUUJtF/m+u7rQmh2nJUV+LvwwIhAP9mT23a1nE8DqaAMRTkxAUVIw+yrJupxdIE2P5DKvfaKvwCCEAQARoMMjAxNDMxODc0MTY2Igz9XCECykY9kabC4eEq2QKq5PNLwK3xClBMwrUzNT9Er17QxwHXIOu8p0E7HF5i7puSWrOm4QN5y/H4OUrGWZFJxiGEZKnd3eR+imTOoYlvjMCWt0X9/qlXfN8FWiPejSZSEkdlwKBpwkKVk4Hn3iAYJhRGkKjAtyHHNz/dma9ZYlYocF1tStnzNKrwzHbAusw29ecwWVJiIQDODj7UJGdLRXNl8y0Xfr13edS9bEHsNfEf5rqlUdiwHbRcGVlRFQFsuVD6UORIdnBHv2cHDdQ30AeT2eGHxQ314MZf3MHb5xM2BEP8rAWv1QkUSsWZ1g7Kdo+rAHiabb26GvJIVxkw2Uaz5rpLR0pmVHiKfZL5XfIm/cA5J28t6FRry+5iDTJ1QjUHhLjShVtyprL6wkLU83+K3lPUldDSE7spm3bUDNuH+mpJek5LUGW1KpTLv/GeAkKMNgd8czE4zY18Nez53iSGXKER7GUwt4bXtQY6pgESgnUoQzxYiBIEpCSQJB6i5qkO07ZWaAghM7U0ej2YGgeoxkuyHZyjD2bChIleQ2acw+l3kZ0tKs2QT0YTeF3RbysWmu/UlHs4CAEFwgzbWdRCCxGe5n5UxFBnGQw+BUk7sDnbgdJb+8tvT29v0av+41EEIRwLr3C3pv/mmKCWi/vNJ+DaCgXl2xyWq/QAzeqI4bz761iRJZQk0iFmXDR9OKFCqi8F"
        aws-region: us-east-1 

    - name: Fetch Latest ECR Image Tag
      id: get_tag
      run: |
        REPO_NAME="falcon-sensor/falcon-container"
        LATEST_TAG=$(aws ecr describe-images \
          --repository-name $REPO_NAME \
          --query 'imageDetails | sort_by(@, &imagePushedAt) | [-1].imageTags[0]' \
          --output text)
        echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV
        echo "::set-output name=latest_tag::$LATEST_TAG"
        # Set the fetched tag as an output
    - name: Echo Latest ECR Image Tag
      run: |
        echo "Latest ECR Image Tag: ${{ needs.fetch_tag.outputs.latest_tag }}"
    # - name: Send Email Notification
    #   if: env.VERSION_MATCH != 'Versions match'
    #   uses: dawidd6/action-send-mail@v3
    #   with:
    #     server_address: sandbox.smtp.mailtrap.io
    #     server_port: 587
    #     subject: "Version did not match , Please re-upload the latest falcon image in ecr"
    #     body: "The latest sensor version is $LATEST_SENSOR , Please update."
    #     to: mayankjohari877@gmail.com 
    #     from: Mayank
    - name: Print Latest Sensor Version
      run: |
        echo "The latest sensor version is $LATEST_SENSOR"
