name: Falcon API Request
on:
  push:
    branches:
      - main
permissions:
  id-token: write 
  contents: read 
jobs:
  request:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Make Falcon API Request
      id: falcon
      env:
        FALCON_CLIENT_ID: "19e063dd2f834679b091dfea627450c5"
        FALCON_CLIENT_SECRET: "ier9dDPOpWcz7ybmZM1FCG8S0JHLju4sK5k36A2o"
        FALCON_CID: "A3839C9ECA014C70B7DB136F279AE499-C7"
      run: |
        LATEST_SENSOR=$(FALCON_CLIENT_ID=$FALCON_CLIENT_ID \
                        FALCON_CLIENT_SECRET=$FALCON_CLIENT_SECRET \
                        FALCON_CID=$FALCON_CID \
                        bash <(curl -Ls https://github.com/CrowdStrike/falcon-scripts/releases/latest/download/falcon-container-sensor-pull.sh) \
                        -t falcon-container | tail -1)
        echo "LATEST_SENSOR=$LATEST_SENSOR" >> $GITHUB_OUTPUT

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: "ASIAS5ZSGPJ3CSLB4TND"
        aws-secret-access-key: "0uCwQ4HIW7OG6drEf7hom0sZkfqi8dn0Kd2oxHdt"
        aws-session-token: "IQoJb3JpZ2luX2VjEJH//////////wEaCXVzLWVhc3QtMSJIMEYCIQCXiPFB9Y0xrcQLVhGjq3xhIB+ilLUK7AW+1+EQeUZrQQIhANg5aJAVfZOKyWASc35dPpEYzfzdQCas7Gat+s9fwb6OKoUDCIr//////////wEQARoMMjAxNDMxODc0MTY2IgzXoz40iy+zVzl5rrwq2QKKKZRLgF8D7b4MIIJD+jw/JEHvYP87qVh6noRiQuy8SMbajEKOjVKI5yeHJZBd+VilLjamnTsv4kAQaLUYB/YAaJbA3tAKuf8n7ICJHXfLiaRBOR0JeAlLYUSIe7xb11/JdmXrpFrJ04UMX5PfphkC/YuagQa9S5ioqlV5rcTTQsPM85TAjvwISVRvXeTZzExKG3TivBItjmkJxcINtIAipeG+FbU38FmiqUk06LYsfdOUtwNa3saPzrDpxaMY8TwRikkhL3D5Wm+A31DKaOk76xJ0kleaX4KFlafA8wc0MLZA0Da2cimqBU8ba4ZOB9Xa76Ov3GnxMb/kLr2XhqkjTxkh0FYfU6DYn3keLgoIUtNxx53I88iGiouT7HiBeBtkUADnK3bQdYUUmI6OClMw0P+EPY4Qg3iX0wAv0TqufLuwxRBLHZoAjWNgEAsioUuAae9vTNAuQ1Awv5nntQY6pgEfFIiarw0pBPZNYzr6fe7Kv8T8Lig2TrytrRJrBkPDTmUzBahM2BlgmejuquHqjCnIJlC5jvXKYlwAXT7LQ1Gny0x+9zEA4w1kRvwoFJGB4mF2texrt744yh1tu+A26S6LU6Oe0yfJ3O/+ctL1EMWCtvCQDcPUb2MloZXCpbq7s8zRwSdgbKNdZhbBfC8Kygpz5pL69tovuILiSX4SGwwwS1cJM/l4"
        aws-region: us-east-1 
          # Logging to AWS
    # - name: Configure AWS credentials
    #   uses: aws-actions/configure-aws-credentials@v4
    #   with:
    #         role-to-assume: arn:aws:iam::201431874166:role/acs-sso-dev-oidcsrole
    #         role-session-name: "acsdevrolesession"
    #         aws-region: us-east-1
    
    - name: Fetching the ecr image tag
      id: check-ecr-image
      uses: mnmandahalf/check-ecr-image-exists@v0.1.5
      with:
          region: us-east-1
          repository-name: "falcon-sensor/falcon-container"
          image-tag: ${{steps.falcon.outputs.LATEST_SENSOR}}
  
    - name: Perform other action based on the output
      if: ${{ steps.check-ecr-image.outputs.image-exists == '0' }}
      run: |
        echo "Version dont match"  

    - name: Approval Job
      if: ${{ steps.check-ecr-image.outputs.image-exists == '0' }}
      with:
          environment: FALCON_UPDATION 












    # - name: Fetch Latest ECR Image Tag
    #   id: get_tag
    #   run: |
    #     REPO_NAME="falcon-sensor/falcon-container"
    #     LATEST_TAG=$(aws ecr describe-images \
    #       --repository-name $REPO_NAME \
    #       --query 'imageDetails | sort_by(@, &imagePushedAt) | [-1].imageTags[0]' \
    #       --output text)
    #     echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV
    #     echo "::set-output name=latest_tag::$LATEST_TAG"
    #     # Set the fetched tag as an output
    # - name: Echo Latest ECR Image Tag
    #   run: |
    #     echo "Latest ECR Image Tag: ${{ needs.fetch_tag.outputs.latest_tag }}"
    # - name: Send Email Notification
    #   if: env.VERSION_MATCH != 'Versions match'
    #   uses: dawidd6/action-send-mail@v3
    #   with:
    #     server_address: sandbox.smtp.mailtrap.io
    #     server_port: 587
    #     subject: "Version did not match , Please re-upload the latest falcon image in ecr"
    #     body: "The latest sensor version is $LATEST_SENSOR , Please update."
    #     to: mayankjohari877@gmail.com 
    #     from: Mayank
    # - name: Print Latest Sensor Version
    #   run: |
    #     echo "The latest sensor version is $LATEST_SENSOR"
