name: Falcon API Request

on:
  push:
    branches:
      - main

jobs:
  request:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Make Falcon API Request
      env:
        FALCON_CLIENT_ID: "19e063dd2f834679b091dfea627450c5"
        FALCON_CLIENT_SECRET: "ier9dDPOpWcz7ybmZM1FCG8S0JHLju4sK5k36A2o"
        FALCON_CID: "A3839C9ECA014C70B7DB136F279AE499-C7"
      run: |
        response=$(curl -X POST "https://api.crowdstrike.com/your-api-endpoint" \
          -H "Content-Type: application/json" \
          -d '{
            "client_id": "'"$FALCON_CLIENT_ID"'",
            "client_secret": "'"$FALCON_CLIENT_SECRET"'",
            "cid": "'"$FALCON_CID"'"
          }')

        echo "Response: $response"
