name: Falcon API Request
on:
  push:
    branches:
      - main
jobs:
  request:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Make Falcon API Request
      env:
        FALCON_CLIENT_ID: "19e063dd2f834679b091dfea627450c5"
        FALCON_CLIENT_SECRET: "ier9dDPOpWcz7ybmZM1FCG8S0JHLju4sK5k36A2o"
        FALCON_CID: "A3839C9ECA014C70B7DB136F279AE499-C7"
      run: |
        # Fetch the latest sensor version with required environment variables
        LATEST_SENSOR=$(FALCON_CLIENT_ID=$FALCON_CLIENT_ID \
                        FALCON_CLIENT_SECRET=$FALCON_CLIENT_SECRET \
                        FALCON_CID=$FALCON_CID \
                        bash <(curl -Ls https://github.com/CrowdStrike/falcon-scripts/releases/latest/download/falcon-container-sensor-pull.sh) \
                        -t falcon-container | tail -1)
        echo "LATEST_SENSOR=$LATEST_SENSOR" >> $GITHUB_ENV

    - name: Compare Sensor Version
      id: compare
      run: |
        PREDEFINED_VERSION="1.2.3" 
        # Compare the fetched sensor version with the predefined version
        if [ "$LATEST_SENSOR" == "$PREDEFINED_VERSION" ]; then
          echo "Versions match" 
        else
          echo "Versions do not match" 
        fi

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: "AKIAZI2LDKXUFJTQKZGM"
        aws-secret-access-key: "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"
        aws-region: us-east-1 

    - name: Fetch Latest ECR Image Tag
      id: fetch_tag
      run: |
        # Fetch the latest image tag from the ECR repository
        REPO_NAME="acs-sso-efs-dev-ecr"
        LATEST_TAG=$(aws ecr describe-images \
          --repository-name $REPO_NAME \
          --query 'imageDetails | sort_by(@, &imagePushedAt) | [-1].imageTags[0]' \
          --output text)
        echo "ECR_TAG=$LATEST_TAG" >> $GITHUB_ENV
    # - name: Send Email Notification
    #   if: env.VERSION_MATCH != 'Versions match'
    #   uses: dawidd6/action-send-mail@v3
    #   with:
    #     server_address: sandbox.smtp.mailtrap.io
    #     server_port: 587
    #     subject: "Version did not match , Please re-upload the latest falcon image in ecr"
    #     body: "The latest sensor version is $LATEST_SENSOR , Please update."
    #     to: mayankjohari877@gmail.com 
    #     from: Mayank
    - name: Print Latest Sensor Version
      run: |
        echo "The latest sensor version is $LATEST_SENSOR"
