name: workflow_02
on:
  repository_dispatch:
    types:
      - trigger-workflow_02
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
   # your existing steps of workflow
