name: My Target Workflow

on:
  push:

jobs:
  approval:
    runs-on: ubuntu-latest
    environment: stage  # Define the environment for the job

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      # Create a text file with "Hello World" content
      - name: Create test file
        run: echo hello World > test.txt

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: test.txt

      - name: Use Custom Action to Delete Artifact
        uses: geekyeggo/delete-artifact@v2
        with:
          name: my-artifact

          timeout:
            runs-on: ubuntu-latest  # Or your preferred runner OS
            steps:
              - name: Wait for context information (Option 1: wait step)
                uses: actions/github-script@v6
                with:
                  script: |
                    # Wait until context information is available
                    while (github.event === undefined) {
                      core.info("Waiting for context information...");
                      sleep(5);  # Adjust wait time as needed (seconds)
                    }
        
              - name: Wait for context information (Option 2: loop)  # Alternative approach
                run: |
                  while (github.event.workflow_run === undefined); do
                    echo "Waiting for context information..."
                    sleep 5  # Adjust wait time as needed (seconds)
                  done
        
              - name: Check approval status
                uses: actions/github-script@v6
                with:
                  script: |
                    if (github.event.workflow_run.conclusion === 'waiting') {
                      core.setFailed('Approval job not approved!');
                    }
              - name: Wait for 24 hours
                run: sleep 86400  # Sleeps for 24 hours (86400 seconds)
              - name: Cancel workflow if not approved
                uses: actions/github-script@v6
                with:
                  script: |
                    core.cancelWorkflow();