name: My Target Workflow

on:
  push:

jobs:
  approval:
    runs-on: ubuntu-latest
    environment: stage

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create test file
        run: echo "hello World" > test.txt

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: test.txt

      - name: Use Custom Action to Delete Artifact
        uses: geekyeggo/delete-artifact@v2
        with:
          name: my-artifact

  timeout:
    runs-on: ubuntu-latest

    steps:
      - name: Set start time
        id: set_start_time
        run: echo "##[set-output name=start_time]$(date +%s)"

      - name: Check approval status with timeout
        id: check_approval
        uses: actions/github-script@v6
        with:
          script: |
            const startTime = parseInt(process.env.startTime);
            let currentTime = Math.floor(Date.now() / 1000);
            console.log(startTime);

            while (!github.event || !github.event.workflow_run || github.event.workflow_run.conclusion === undefined && (currentTime - startTime) < 30) {
              console.log("Waiting for approval status (", (currentTime - startTime), "seconds passed)");
              await new Promise(resolve => setTimeout(resolve, 5000));  // Wait for 5 seconds
              currentTime = Math.floor(Date.now() / 1000);
            }

            if (!github.event || !github.event.workflow_run || github.event.workflow_run.conclusion === undefined) {
              core.setFailed('Approval job status undefined for more than 30 seconds!');
              core.cancelWorkflow();
            } else {
              console.log("Approval job status received:", github.event.workflow_run.conclusion);
            }
