name: My Target Workflow

on:
  workflow_call:
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      # Create a text file with "Hello World" content
      - name: Create test file
        run: echo hello World> test.txt
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: test.txt
      - uses: geekyeggo/delete-artifact@v5
        with:
          name: my-artifact
