name: My Target Workflow

on:
  push:

jobs:
  approval:
    runs-on: ubuntu-latest
    environment: stage

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create test file
        run: echo "hello World" > test.txt

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: test.txt

      - name: Use Custom Action to Delete Artifact
        uses: geekyeggo/delete-artifact@v2
        with:
          name: my-artifact

  timeout:
    runs-on: ubuntu-latest

    steps:
      - name: Set start time
        id: set_start_time
        run: echo "##[set-output name=start_time]$(date +%s)"

      - name: Wait for 30 seconds
        run: sleep 30s

      - name: Check approval status  # Execute only if the previous step failed (timeout)
        run: |
          echo "Approval job status check after timeout"
          echo "Initiating cancellation of the workflow run..."

          # Obtain necessary details for the cancellation
          export OWNER=$GITHUB_REPOSITORY_OWNER
          export REPO=$GITHUB_REPOSITORY
          export RUN_ID=$GITHUB_RUN_ID

          # Make API call to cancel the workflow run using curl
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHU_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/$OWNER/$REPO/actions/runs/$RUN_ID/cancel

          exit 1  # Exit with an error code to force cancel the workflow

      - name: Final cleanup or additional steps
        if: always()  # Always execute, regardless of previous steps
        run: |
          echo "Final cleanup or additional steps"
