name: My Target Workflow

on:
  workflow_call:
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      # Create a text file with "Hello World" content
      - name: Create Hello World File
        run: |
          echo "Hello World" > hello.txt
          ls -l  # Optional: List files to verify the creation of hello.txt
