name: My Target Workflow

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: stage  # Define the environment for the job

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      # Create a text file with "Hello World" content
      - name: Create test file
        run: echo hello World > test.txt

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: test.txt

      - name: Use Custom Action to Delete Artifact
        uses: geekyeggo/delete-artifact@v2
        with:
          name: my-artifact
