name: My Target Workflow

on:
  push:
permissions: write-all

jobs:
  approval:
    runs-on: ubuntu-latest
    environment: stage

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        if: always()

      - name: Create test file
        run: echo "hello World" > test.txt

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: test.txt

      - name: Use Custom Action to Delete Artifact
        uses: geekyeggo/delete-artifact@v2
        with:
          name: my-artifact

  timeout:
    runs-on: ubuntu-latest

    steps:
      - name: Set start time
        id: set_start_time
        run: echo "##[set-output name=start_time]$(date +%s)"

      - name: Wait for 30 seconds
        run: sleep 30s

      - name: Check approval status
        # uses: styfle/cancel-workflow-action@0.9.1
        # with:
        #   workflow_id: ${{ github.workflow_id }}
        # if: ${{ failure() }}  # Execute only if the previous step failed (timeout)
        run: |
          echo "Approval job status check after timeout"
          echo "Initiating cancellation of the workflow run..."

          export RUN_ID=${{ github.run_id }}
          # echo "$RUN_ID"
          echo "RUN_ID: $RUN_ID"
          echo "END OF run id"
          export TOKEN=${{ github.token }} 
          echo "$TOKEN"
          echo "END OF LINE"
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer $TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/mayankmj/repo-2/actions/runs/$RUN_ID/cancel"

          exit 1  # Exit with an error code to force cancel the workflow
        
