name: Update falcon image
# This workflow is triggered to upload the latest Falcon image in ECR

on:
  workflow_dispatch:
    inputs:
      env:
        description: "stage | dev | prod"
        type: string
        required: true
      role-to-assume:
        description: "AWS Role arn"
        type: string
        required: true
      role-session-name:
        description: "AWS Role session name"
        type: string
        required: true
      aws-region-name:
        description: "AWS region name"
        type: string
        required: true
      aws-kms-key-arn:
        description: "AWS kms key arn"
        type: string
        required: true
      ecr-repo-name:
        description: "AWS ECR repo name"
        type: string
        required: true
      falcon_image_path:
        description: "Falcon image path"
        type: string
        required: true
      falcon_image_latest_tag:
        description: "Falcon image latest tag"
        type: string
        required: true

jobs:
   Deploy-latest-image-tag: 
    runs-on: ubuntu-latest
    environment:
        name: ${{ inputs.env }}
    steps:
        # Logging to AWS
        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v4
          with:
            role-to-assume: ${{ inputs.role-to-assume }}
            role-session-name: ${{ inputs.role-session-name }}
            aws-region: ${{ inputs.aws-region-name }} 
            
        # Logging to AWS ECR
        - name: Login to Amazon ECR
          id: login-ecr
          uses: aws-actions/amazon-ecr-login@v2.0.1

        # Calling Falcon Composite runner
        - name: Authenticating Crowdstrike
          id: composite
          uses: Americanchemicalsociety/acs-sso-infra/.github/actions/falcon@feature/falcon-updation
          with:
            aws-kms-key-arn: ${{inputs.aws-kms-key-arn}}
            env: ${{ inputs.env }}
            
        # Pushing the latest Falcon image     
        - name: Push latest falcon image
          id: falcon
          run: |
             LATESTSENSOR=$(bash <(curl -Ls https://github.com/CrowdStrike/falcon-scripts/releases/latest/download/falcon-container-sensor-pull.sh ) -u ${{steps.composite.outputs.FALCON_CLIENT_ID}} -s ${{steps.composite.outputs.FALCON_CLIENT_SECRET}} -t falcon-container | tail -1 )
             docker tag "$LATESTSENSOR" ${{ steps.login-ecr.outputs.registry }}/${{ inputs.ecr-repo-name }}:${{ inputs.falcon_image_latest_tag }}
             docker push ${{ steps.login-ecr.outputs.registry }}/${{ inputs.ecr-repo-name }}:${{ inputs.falcon_image_latest_tag }}    