name: TFSEC Scan

on:
  push:
    branches:
      - main

jobs:
  tfsec:
    name: Run tfsec
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up tfsec
        uses: tfsec/tfsec-action@v1
        with:
          version: 'latest'

      - name: Run tfsec
        run: tfsec .
